-- AlterTable
ALTER TABLE "User" ADD COLUMN "pterodactylUserId" INTEGER;

-- AlterTable
ALTER TABLE "Server" ADD COLUMN "cpu" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN "disk" DOUBLE PRECISION NOT NULL DEFAULT 10;
