-- AlterTable
ALTER TABLE "PremiumOrder" ADD COLUMN "ram" DOUBLE PRECISION;
ALTER TABLE "PremiumOrder" ADD COLUMN "cpu" DOUBLE PRECISION;
ALTER TABLE "PremiumOrder" ADD COLUMN "disk" DOUBLE PRECISION;
